### ISSUE TITLE
Pipeline fails at `draco.analysis.sensitivity.ComputeSystemSensitivity` due to MPIArray issue.

### ISSUE THREAD

**Issue by ljgray** [chime-experiment/ch_pipeline#106]
The pipeline fails at the aforementioned step, line 213, due to the following error in  `mpiarray _mpi_to_ndarray`:
```python
raise ValueError("Only MPIArrays or None values are allowed.")
```
on radiocosmology/caput@40ca0865d2456ce9f59ae1106dc52a5626d72859 (most recent commit).
I am putting this issue here because this seems to be a wider issue with the pipeline rather than `mpiarray` itself. Several steps, including `ch_pipeline.analysis.calibration.CorrectTelescopeRotation`, are causing the following warning:

> WARNING  py.warnings: .../caput/caput/mpiarray.py:1782: UserWarning: A ufunc is combining an MPIArray with a numpy array that matches exactly the local part of the distributed axis. This is very fragile and may fail on other ranks. Numpy array shape: (4, 16356, 1); dist axis: 0.

**Comment by ljgray** [comment]
This issue occurs when a ufunc is called with an np.ndarray output and an mpiarray input.

**Comment by jrs65** [comment]
I'm pretty sure I've fixed all of these errors in my own branches. Let me try and push everything up.

**Comment by ljgray** [comment]
I've come to the root of the issue so I'll check if it's fixed. It happens if, for example, you do `y += x` where y is a numpy.ndarray and x is an mpiarray

**Comment by jrs65** [comment]
Indeed. There were a handful of instances across the pipeline that I've fixed. I think it makes sense to disallow this, although it has been annoying fixing them all.

**Comment by ljgray** [comment]
Agreed. Might be worth adding a more explicit error when it happens. Something like 
```python
 if not all(isinstance(x, MPIArray) for x in out_args):
    raise TypeError
```
before calling `_mpi_to_ndarray` in `__array_ufunc__`

**Comment by ljgray** [comment]
This appears to be fixed.
