### ISSUE TITLE
Proper handling of chimeN2, chimpb, and chimestack data products

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/ch_pipeline#11]
moved from bitbucket. Author: @ssiegelx 

@nritsche 
- Create (or identify) task that finds files based on acquisition name. Put in ch_pipeline/io.py.
- Add the ability to generate the telescope class independent of beam transfer matrices.

@tristpinsm 
- CollateProducts should check for existing index_map/stack, reverse_map/stack, flags/inputs, and generate the number of baselines that have been stacked.

@ssiegelx 
- Update CollateProducts to use different weighting schemes when averaging over redundant baselines (Inverse variance, number of baselines that went into the stack)

@fandinomat 
- Update draco.core.container.TimeStream to hold index_map/stack, reverse_map/stack, flags/inputs, and (possibly) gains.
- Update CollateProducts to create a index_map/stack and reverse_map/stack that is saved in the TimeStream container.

**Comment by jrs65** [comment]
No one understands what this is.
