### ISSUE TITLE
flagging warning over MPI ufunc

### ISSUE THREAD

**Issue by xzackli** [chime-experiment/ch_pipeline#245]
https://github.com/chime-experiment/ch_pipeline/blob/3d74271fa249209f1af6722ab189bce286e529fd/ch_pipeline/analysis/flagging.py#L2122

In the @ljgray `lg/rebin-weight-masks` branch, there is some scary rebin_weight action that dumps hundreds of warnings when I generate quarterstacks:

```
  9979.2s [MPI 122/128] - WARNING  py.warnings: /project/6003614/zackli/pipeline2/chime_env/code/ch_pipeline/ch_pipeline/analysis/flagging.py:2122: UserWarning: A ufunc is combining an MPIArray with a numpy array that matches exactly the local part of the distributed axis. This is very fragile and may fail on other ranks. Numpy array shape: (8, 4096); dist axis: 0.
  timestream.rebin_weight[:] *= weight_mask[:, 0]
```

I converted the sstack of the rev_08 fullstacks with the VisGrid task and generated some ringmaps that looked super weird — I'll do some digging but this might be part of it?

**Comment by ljgray** [comment]
Ah, yeah the way distributed arrays are implemented will throw a warning, but the behaviour is still ok. I'll fix the warning in the morning, but it won't affect weirdness with ringmaps

**Comment by ljgray** [comment]
I'd be curious to see the ringmap weirdness

**Comment by ljgray** [comment]
I'm going to close this issue because we've gotten rid of the `rebin-weight-masks1 branch
