### ISSUE TITLE
Port `ch_pipeline.analysis.solar` to the new ephemeris code

### ISSUE THREAD

**Issue by jrs65** [chime-experiment/ch_pipeline#64]
The refactored ephemeris code in `ch_util`/`caput` doesn't support PyEphem calls any more. This looks like it will have broken the solar analysis module. I had a quick look at fixing it, and while most is easy, one section looked a little more involved (calls around `peak_RA` IIRC).

From memory the easy changes are:
- `ephemeris._get_chime` -> `ephemeris.chime`
- Remove `ra_dec_of` and use `ephemeris.object_coords`

**Comment by ssiegelx** [comment]
This is done as of PR #135 .  The relevant changes are in the `analysis.solar.sun_coord` method.
